### ISSUE TITLE
Not working on windows currently. 

### ISSUE THREAD

**Issue by leet0rz** [Exafunction/codeium.nvim#103]
After navigating through a minefield of errors, I finally get no errors and codeium starts with the following message: `Codeium.nvim: server updated` the completion does not work however.

**Comment by WillEhrendreich** [comment]
ok, so I think I have things fixed, I have a pr for the windows problems I know about. Take a look Here: https://github.com/Exafunction/codeium.nvim/pull/105 

Once my pr gets accepted, this should work for people on windows, that seems to clear the errors. 

As for the cmp integration, I'd encourage you to take a look at @folke's implementation of it in his extras of lazyvim. https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/coding/codeium.lua

**Comment by leet0rz** [comment]
> ok, so I think I have things fixed, I have a pr for the windows problems I know about. Take a look Here: #105
> 
> Once my pr gets accepted, this should work for people on windows, that seems to clear the errors.
> 
> As for the cmp integration, I'd encourage you to take a look at @folke's implementation of it in his extras of lazyvim. https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/coding/codeium.lua

Yeah I were able to get past all the errors by myself but the completion does not work, it does not work with lazyvim's setup either and it should not depend on lazyvim's setup. There should be clear guidance on this plugin how to make it work, which I've followed to a T and there is no completion. Completion works for everything else I am using, but not Codeium.

Just letting you know.

**Comment by leet0rz** [comment]
> Did you do `:Codeium Auth`?

Yep, and entered the token successfully.

**Comment by leet0rz** [comment]
I retried the codeium vim version, installed manually and did the auth in powershell and now it works. The Auth would not work with git-bash.

Not sure if the manually downloading was needed or not but try authing with powershell if you are having this issue.

**Comment by folke** [comment]
no idea. You'll need to check with codeium-nvim, not a LazyVim issue

**Comment by leet0rz** [comment]
> no idea. You'll need to check with codeium-nvim, not a LazyVim issue

Well yeah, this is a Codeium thread and the other person might have pinged you.

**Comment by leet0rz** [comment]
> Right, my bad :)

No worries, we've spoken over a few threads so easily mixed up :)
