### ISSUE TITLE
Weird behavior while completing code

### ISSUE THREAD

**Issue by Pagliacii** [Exafunction/codeium.nvim#108]
## Behavior

I wrote this comment: "Implement the fib function" and pressed enter key. Then, if I enter `def`, the completing candidate would only have the function signature. If I enter `def` first, then ` f`, the completing candidate would contain the function body this time.

![image](https://github.com/Exafunction/codeium.nvim/assets/12871143/c3c21a17-80d0-4d1b-9ed8-07a0f01c9124)

![image](https://github.com/Exafunction/codeium.nvim/assets/12871143/a0f49839-5e5a-4b4d-a43b-b1a2fdc2a753)

## Environments

- OS: Windows 11
- Editor: NVIM v0.10.0-dev-1031+gc431d820e
- Config: LazyVIM Extras codeium

**Comment by fortenforge** [comment]
This is working as intended. We have some systems in place to determine if we should give back single-line or multi-line suggestions.
