### ISSUE TITLE
Codeium language server executable throws error on Windows

### ISSUE THREAD

**Issue by andreadev-it** [Exafunction/codeium.nvim#111]
Hello,
Today I've updated my plugins in neovim and now whenever I start neovim, this error gets thrown:
```
Error/s executing function codeium#server#Start[36]..<SNR>54_ActuallyStart:
riga   16:
E903: Process failed to start: unknown error: "C:\Users\Test/.codeium/bin/39080e89780bea461f7a46e6dc1026d80a3a353a/language_server_windows_x64.exe"
```

I tried moving the bin directory to force a regeneration, and even though it was recreated, the language server still fails to start. I tried also to just execute that binary from the powershell, but it states that "the specified executable is not a valid application for this operating system":
```
Impossibile eseguire il programma 'language_server_windows_x64.exe': L'eseguibile specificato non è un'applicazione valida per questo sistema operativo.In riga:1 car:1
+ .\language_server_windows_x64.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
In riga:1 car:1
+ .\language_server_windows_x64.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

The folder containing the language server is: `39080e89780bea461f7a46e6dc1026d80a3a353a`

Is there somthing else I can try?

**Comment by pqn** [comment]
What's your operating system/architecture?

**Comment by andreadev-it** [comment]
I've got Windows 10 pro (10.0.19045)
I'm using the Windows Terminal with neovim v. 0.8.0-1210

**Comment by andreadev-it** [comment]
I've just updated to the latest version and it started working again

**Comment by pqn** [comment]
Great, feel free to create a new issue if you have errors.

**Comment by LeonardoMor** [comment]
Getting exactly the same thing with the enterprise version. I'm on Windows 11 with the latest version of Codeium

**Comment by Guru521** [comment]
@LeonardoMor
Hi,

I'm a Codeium.vim user and encountered the same problem. I was able to resolve it by:
1. Visiting [this page](https://github.com/Exafunction/codeium/tags)
2. Downloading `language-server-v1.8.45`.
3. Replacing the file at %homepath%/.codeium/bin/{ID}/language_server_windows_x64.exe with the downloaded version.

I hope this helps!

**Comment by JohnnyCarreiro** [comment]
I facing the same problem with the windows_x64.exe binary. But what is really stranger is the fact I'm on a Mac. I downloaded the Mac Os binary and install on HOME/.codeium/bin/{id}/language_server_macos_x64 and I deleted windows exe. But every time I restart nvim codeium recreates windows executable

**Comment by vishnu81** [comment]
> [@LeonardoMor](https://github.com/LeonardoMor) Hi,
> 
> I'm a Codeium.vim user and encountered the same problem. I was able to resolve it by:
> 
> 1. Visiting [this page](https://github.com/Exafunction/codeium/tags)
> 2. Downloading `language-server-v1.8.45`.
> 3. Replacing the file at %homepath%/.codeium/bin/{ID}/language_server_windows_x64.exe with the downloaded version.
> 
> I hope this helps!
> 
> PS. Remove %homepath%/.codeium/bin/{ID}/language_server_windows_x64.exe and restart neovim also worked for me.

this worked for Pycharm 2025.1 on Windows 11, Windows defender kept blocking this exe file in .codemium,
once I downloaded as this reply, and updated in codemium folder, it worked.
