### ISSUE TITLE
Configure with Codeium Enterprise server

### ISSUE THREAD

**Issue by plague-doctor** [Exafunction/codeium.nvim#113]
How can I specify my own Enterprise server?
I have tried:
```
{
    "Exafunction/codeium.nvim",
    dependencies = {
        "nvim-lua/plenary.nvim",
        "hrsh7th/nvim-cmp",
    },
opts = {
   api = { host = "https://my-codeium.com/_route/api_server", port = 443}
   }
},
```
I can't see any error, but the config is ignored and `:Codeium Auth` takes me to official codeium url.

While using `codeium.vim` works fine with:
```
vim.cmd[[let g.codeium_server_config = {
  \'portal_url': 'https://my-codeium.com',
  \'api_url': 'https://my-codeium.com/_route/api_server' }
]]
```

**Comment by pqn** [comment]
This extension hasn't been converted to enterprise support yet like https://github.com/Exafunction/codeium.vim. If you're one of our enterprise customers interested in using this, would you mind also requesting this via a non-GitHub channel (email, ticket, Slack, etc.)?

**Comment by plague-doctor** [comment]
@pqn Done ;-)

**Comment by consoleaf** [comment]
Please try now, this should be supported.

**Comment by EricTheMagician** [comment]
I've been using it for a couple of weeks now and it works great!
