### ISSUE TITLE
bug: Codeium Profile Completions/Total Completions not updated after completion accepted

### ISSUE THREAD

**Issue by cleong14** [Exafunction/codeium.nvim#124]
Tested and confirmed only codeium.nvim fails to update completions count; codeium.vim updates completions count as expected.

**Comment by milanglacier** [comment]
I can confirm with this. In the personal homepage, I see that the number of accepted completions from Neovim will not increase.

**Comment by pqn** [comment]
This will require implementing calling the `AcceptCompletion` RPC in the extension. This is where it's called in other extensions for example:
* https://github.com/Exafunction/codeium.vim/blob/c18f6642f2bd071ab0154e5d333697067f9c4b70/autoload/codeium.vim#L83
* https://github.com/Exafunction/CodeiumVisualStudio/blob/1b846dc79b12256330879f1b2613178be06197fd/CodeiumVS/Proposal/CodeiumProposalSourceProvider.cs#L80

**Comment by cleong14** [comment]
@pqn thank you for the additional context!

If I have time, I'll try take a stab at this feature and I'll see if I can figure it out.

**Comment by milanglacier** [comment]
> @pqn thank you for the additional context!
> 
> If I have time, I'll try take a stab at this feature and I'll see if I can figure it out.

This is a proprietary software and it is their responsibility to polish the software delivered to their user.

**Comment by milanglacier** [comment]
> This will require implementing calling the `AcceptCompletion` RPC in the extension. This is where it's called in other extensions for example:
> 
> * https://github.com/Exafunction/codeium.vim/blob/c18f6642f2bd071ab0154e5d333697067f9c4b70/autoload/codeium.vim#L83
> * https://github.com/Exafunction/CodeiumVisualStudio/blob/1b846dc79b12256330879f1b2613178be06197fd/CodeiumVS/Proposal/CodeiumProposalSourceProvider.cs#L80

cmp has a hook cmp.event.on:("confirmation_done") which can be used to send the AcceptCompletion request.

**Comment by fortenforge** [comment]
> This is a proprietary software and it is their responsibility to polish the software delivered to their user.

We at Codeium were not the original authors of this plugin. We simply took it over when the original maintainer and author archived it.

**Comment by cleong14** [comment]
>> This is a proprietary software and it is their responsibility to polish the software delivered to their user.
>
> We at Codeium were not the original authors of this plugin. We simply took it over when the original maintainer and author archived it.

Additionally, per the [LICENSE](https://github.com/Exafunction/codeium.nvim/blob/main/LICENSE) and the [Contributing](https://github.com/Exafunction/codeium.nvim#contributing) section of the README, Issues & PRs are accepted.

**Comment by milanglacier** [comment]
#132 should solve this.

**Comment by cleong14** [comment]
@milanglacier when you tested your changes, were you able to validate that your profile updated correctly each time you accepted a completion item?

**Comment by milanglacier** [comment]
> @milanglacier when you tested your changes, were you able to validate that your profile updated correctly each time you accepted a completion item?

Of course They did update.

**Comment by cleong14** [comment]
Awesome.

Maybe it was an anomaly or some discrepancy in my config at the time, but when I tested your changes my profile still only received intermittent updates on completion acceptance.

Glad to hear it works though; thanks for creating the fix & PR!

**Comment by milanglacier** [comment]
> Awesome.
> 
> Maybe it was an anomaly or some discrepancy in my config at the time, but when I tested your changes my profile still only received intermittent updates on completion acceptance.
> 
> Glad to hear it works though; thanks for creating the fix & PR!

I use the `tab` key which is mapped to `cmp.mapping.confirm { select = true },`. I believe `cmp.confirm` function must be called so that the hook will be triggered and the `AcceptCompletion` request will send.

**Comment by cleong14** [comment]
> > Awesome.
> > Maybe it was an anomaly or some discrepancy in my config at the time, but when I tested your changes my profile still only received intermittent updates on completion acceptance.
> > Glad to hear it works though; thanks for creating the fix & PR!
> 
> I use the `tab` key which is mapped to `cmp.mapping.confirm { select = true },`. I believe `cmp.confirm` function must be called so that the hook will be triggered and the `AcceptCompletion` request will send.

The issue was definitely my `nvim-cmp` config.

The keymap I use to accept/confirm completions was configured to `cmp.mapping.confirm { select = false }`. I think I recall doing this due to confirmed completions overwriting existing text if the completion was accepted in the middle of a line of text.

Changing my config to use `cmp.mapping.confirm { select = true }` when accepting a completion fixed the issue for me and my profile appears to be updating correctly for every completion accepted.

Thanks again for your help with the fix @milanglacier!

**Comment by cleong14** [comment]
fixed in #132
