### ISSUE TITLE
not work on MacOS, unavailable source names

### ISSUE THREAD

**Issue by liaohui5** [Exafunction/codeium.nvim#130]
hello, after `:Codeium Auth`, this plugin still doesn't work on macOS

OS: MacOS sonoma 14.1.1
CPU: intel x86
nvim: NVIM v0.9.4 Build type: Release LuaJIT 2.1.1700008891

When I execute `:CmpStatus`, output like this image

![image](https://github.com/Exafunction/codeium.nvim/assets/29266093/9b95ae50-440d-43a1-a6e2-db790442dab4)

**Comment by milanglacier** [comment]
have you called `require('codeium').setup{}`?

**Comment by liaohui5** [comment]
of course

**Comment by liaohui5** [comment]
> have you called `require('codeium').setup{}`?

of course

**Comment by jakeschurch** [comment]
can confirm same behavior

**Comment by milanglacier** [comment]
I guess this is because codeium is not loaded yet. If you are using lazy as your package manager, add a line `event="InsertEnter"` to make sure lazy is loading codeium at appropriate time and see if it helps.

**Comment by liaohui5** [comment]
> I guess this is because codeium is not loaded yet. If you are using lazy as your package manager, add a line `event="InsertEnter"` to make sure lazy is loading codeium at appropriate time and see if it helps.

I used Lazy.nvim, plugin config like this:
```lua
  {
      "Exafunction/codeium.nvim",
      event = "InsertEnter",
      config = function()
          require("codeium").setup({})
      end,
  }
```

 this plugin still doesn't work on macOS

**Comment by boyo23** [comment]
Maybe add its dependencies? This is how I did it:

```lua
{
  "Exafunction/codeium.nvim",
  event = "InsertEnter",
  dependencies = {
    "hrsh7th/nvim-cmp",
    "nvim-lua/plenary.nvim",
  },
  config = true,
}
```

**Comment by consoleaf** [comment]
I'd try BufRead or VeryLazy as the event. But if you run :Codeium and it doesn't say command not found, it should be available in cmp as well. Just make sure cmp setup is called before codeium setup

**Comment by johnbunky** [comment]
HI @consoleaf thank you for your explanations. 
I've added required changes to cmp and it works again!!
Really appreciate.

**Comment by feekApp** [comment]
@johnbunky could you share your changes. I've a similar issue.

**Comment by johnbunky** [comment]
@feekApp 
Sure, sorry for delay reply.
You can find all my mac setup via the link
https://github.com/johnbunky/nvimTermuxJavaIDE/tree/mac-version
The changes are in 
lua/completion.lua and lua/plug_packer.lua files
Happy coding)

**Comment by feekApp** [comment]
@johnbunky thnx for sharing!

**Comment by stong1994** [comment]
That doesn't work for me. However, after adding the setup code for codeium below nvim-cmp, it works! 
<img width="816" alt="image" src="https://github.com/Exafunction/codeium.nvim/assets/23580595/ba5b4e17-4d85-421f-8049-67fdb59d0304">
