### ISSUE TITLE
Expand-file not work in win11

### ISSUE THREAD

**Issue by R0boter** [Exafunction/codeium.nvim#134]
I found some errors when using powershell for win11, vim.o.shell awlays return cmd.exe,so expand-file never executes, maybe we need change use some other function. I don't know if it's neovim's problem.
(sorry, my english is so bad 😥)
![图片](https://github.com/Exafunction/codeium.nvim/assets/41858428/c2bfff70-dd83-4fa3-b459-bb3f2bdb3c1f)
![图片](https://github.com/Exafunction/codeium.nvim/assets/41858428/ec1691c6-226a-462f-bd47-25ff7780c78d)
Thank you for your help!!!

**Comment by neilfranci** [comment]
vim.o.shell returns the shell that neovim uses as default. You need to change it to powershell manually.
But what does this have to do with the codeium.nvim?

**Comment by R0boter** [comment]
I changed it, but also can't unpack the language_server_windows_x64.exe.gz, I install the language server manually, it's work. if it's not a error, i will close this issue, thank you for your help

**Comment by zhufengning** [comment]
@neilfranci 
When it is found that there is no gzip in the system, it will detect whether the shell is powershell. If it is, it will run the gzip.ps1 script instead.
