### ISSUE TITLE
Error detected while processing function codeium#server#Start:

### ISSUE THREAD

**Issue by samarth-nagar** [Exafunction/codeium.nvim#138]
false alarm this issue is from codeium.vim not codeium.nvim

**Comment by PiyushDuggal-source** [comment]
Hey @samarth-nagar, if you are using codeium.vim, just switch back to previous version, it will fix it for now.
```
	use({
		"Exafunction/codeium.vim",
		commit = "a1c3d6b369a18514d656dac149de807becacbdf7",
	})
```

This works for me ^^

**Comment by samarth-nagar** [comment]
thanks but where do put that commit data?
im using lazy

**Comment by daUnknownCoder** [comment]
> thanks but where do put that commit data? im using lazy

```lua
  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      { "Exafunction/codeium.vim", lazy = true, commit = "a1c3d6b369a18514d656dac149de807becacbdf7" },
      lazy = true,
    },
```

**Comment by daUnknownCoder** [comment]
i too am facing this issue

**Comment by samarth-nagar** [comment]
for anyone whos facing the same issue the fix that @PiyushDuggal-source has given is valid my code looks something like this 
```
return {
  'Exafunction/codeium.vim',
  commit = "a1c3d6b369a18514d656dac149de807becacbdf7",
  config = function()
    -- Change '<C-g>' here to any keycode you like.
    vim.keymap.set('i', '<C-f>', function() return vim.fn['codeium#Accept']() end, { expr = true, silent = true })
    vim.keymap.set('i', '<c-g>', function() return vim.fn['codeium#CycleCompletions'](1) end,
      { expr = true, silent = true })
    vim.keymap.set('i', '<c-d>', function() return vim.fn['codeium#CycleCompletions'](-1) end,
      { expr = true, silent = true })
    vim.keymap.set('i', '<c-x>', function() return vim.fn['codeium#Clear']() end, { expr = true, silent = true })
  end
}
```
but you must go to the (offical repo issue list )[https://github.com/Exafunction/codeium.vim/issues/308] and start an issue there or like the the one issue noticing tht question

**Comment by hisamafahri** [comment]
+1 facing the same issue

**Comment by avtotrainer** [comment]
in locale
cd  ~/.vim/pack/Exafunction/start/codeium.vim
git checkout a1c3d6b369a18514d656dac149de807becacbdf7

**Comment by fortenforge** [comment]
Closing this in favor of https://github.com/Exafunction/codeium.vim/issues/308

(Note that this error is specific to codeium.vim)
