### ISSUE TITLE
feat: inline virtual text suggestion similar to `codeium.vim` project

### ISSUE THREAD

**Issue by rlb101001** [Exafunction/codeium.nvim#14]
Awesome plugin, thank you a lot.

Would it be possible to get suggestions the same way as in `codeium.vim` project? `cmp` is awesome but you need start typing or press C-Space to see suggestions, and suggestions are shown not in the first positions of a long list.

**Comment by jcdickinson** [comment]
I plan to do this eventually, but given that codeium.vim already does this, it's pretty low on my priority list.

**Comment by sigmaSd** [comment]
Hello, thanks for this plugin, just want to say that codeium.vim completion is very buggy, so it would be great if we had a native counterpart (if that's going to improve things)

**Comment by HansPinckaers** [comment]
Hi all, you can enable this feature in cmp itself using:
```
cmp.setup {
  experimental = {
    ghost_text = {hlgroup = "Comment"}
  }
}
```


<img width="235" alt="Screenshot 2023-03-09 at 10 30 55" src="https://user-images.githubusercontent.com/70747/223979697-f0ac2472-9313-42b6-a60d-69b3da800c6e.png">

Now I have to find how to accept multiline completions..

**Comment by zettlrobert** [comment]
@rlb101001 define the cases in which you want suggestions to appear, if that is set you could create some autocommands and fitting augroups to trigger the completion for example on new line after comment

**Comment by 2nthony** [comment]
This feature would be awesome! I feel the `codeium.vim` experience is not good enough 🥲

Similar to `copilot.vim`, I think that's why https://github.com/zbirenbaum/copilot.lua exists.

**Comment by chrisgrieser** [comment]
codeium.nvim with ghost text still isn't on the same level as codium.vim, ascmp's suggestions to not appear on empty lines, and hacking together manual triggering via autocmd also isn't ideal.

Even though it is really wasteful, I actually do run both plugins at the same time right now. I added this snippet to prevent too much interference between the two:

```lua
-- when cmp completion is loaded, clear the virtual text from codium
require("cmp").event:on("menu_opened", function() vim.fn["codeium#Clear"]() end)
```

I also made this FR upstream at cmp, which is about indicating if content is multi-line, something which would be quite relevant for this as well: https://github.com/hrsh7th/nvim-cmp/issues/1636

**Comment by toshmukhamedov** [comment]
+1

**Comment by dimfeld** [comment]
I have a draft PR in #241 which implements this. There's still some work left for it to be ready, but I believe the core functionality is all working if anyone wants to try it out.
