### ISSUE TITLE
enhancement: accept word / line of suggestion

### ISSUE THREAD

**Issue by teocns** [Exafunction/codeium.nvim#152]
Copilot has a simillar feature that allows you to [accept a word](https://github.com/github/copilot.vim/blob/57a0115908895f465eb3476f03a0aaa7096e8fe1/doc/copilot.txt#L145) (or line) ahead within the suggestion. 

I find it as an hindrance coming from Copilot

**Comment by LeonardoMor** [comment]
See [here](https://github.com/Exafunction/codeium.vim/issues/27#issuecomment-1950971278)
