### ISSUE TITLE
codeium.log.log: No such file or directory

### ISSUE THREAD

**Issue by bstaint** [Exafunction/codeium.nvim#155]
On Windows, log will raise:
```
E5108: Error executing lua ...able/Neovim/nvim/remote/plenary.nvim/lua/plenary/log.lua:168: D:\Temp\nvim\codeium/codeium.log.log: No such file or directory
stack traceback:
	[C]: in function 'assert'
	...able/Neovim/nvim/remote/plenary.nvim/lua/plenary/log.lua:168: in function 'info'
	[string ":lua"]:1: in main chunk
```
https://github.com/Exafunction/codeium.nvim/blob/cd5913ff5481229b15186293d1d46dd9500789f9/lua/codeium/log.lua#L4

plenary can't create `codeium` directory, and `log` suffix is excessive.

**Comment by consoleaf** [comment]
That's weird because on Linux that code creates `codeium.log`. I added it because it would fail to create file `codeium` because of an existing directory with the same name.

I'll check what plenary does differently for windows and linux

**Comment by bstaint** [comment]
maybe:
https://github.com/nvim-lua/plenary.nvim/commit/55d9fe89e33efd26f532ef20223e5f9430c8b0c0
