### ISSUE TITLE
codeium server crashed: Maybe lsp error?

### ISSUE THREAD

**Issue by WikiLiu** [Exafunction/codeium.nvim#158]
![image](https://github.com/Exafunction/codeium.nvim/assets/68397119/7aedb68e-2b61-427e-bbf0-ee1b7d732524)

**Comment by WikiLiu** [comment]
E471: Argument required
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:299: post http://127.0.0.1:60797/exa.language_server_pb.LanguageServerService/Heartbeat - curl error exit_code=56 stderr={ "curl: (56) Recv failure: Connection reset by peer" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:299: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:240: in function '_shutdown'

**Comment by WikiLiu** [comment]
Plz check and update version “  "version": "1.6.7"”
Help me thanks @pqn

**Comment by WikiLiu** [comment]
@pqn
codeium.vim is fine, but not good support to Lazynvim

**Comment by pu-007** [comment]
I have the same problem

**Comment by WikiLiu** [comment]
> I have the same problem, maybe #164 can be helpful.

works for me, thank you.
