### ISSUE TITLE
this:

### ISSUE THREAD

**Issue by ismayeelanver** [Exafunction/codeium.nvim#167]
I believe codeium is not enabled over here:
![Screenshot from 2024-04-01 14-27-42](https://github.com/Exafunction/codeium.nvim/assets/147964453/db2c4b20-256c-495c-ac6e-906eb6e30148)

 just tell me how to enable it

**Comment by atkr** [comment]
It's not clear what your issue is, but based on your screenshot it seems like you may not have it configured as one of the sources for nvim-cmp. The instructions to add the source are in the README file of the repo.

**Comment by ismayeelanver** [comment]
all finished check my repo:
https://github.com/ismayeelanver/Coolnvim
