### ISSUE TITLE
codeium.nvim makes NeoVim laggy and unresponsive

### ISSUE THREAD

**Issue by MuhammadSawalhy** [Exafunction/codeium.nvim#190]
I noticed that my NeoVim is laggy during typing which was annoying and slows down me affecting my productivity. After some exploration by disabled and re-enabling some installed plugins, I discovered that codeium.nvim is the source of this lagging.

Here's a screen recording shows exactly how it feels.

https://github.com/Exafunction/codeium.nvim/assets/42011920/5929a38f-601f-4a6b-9d90-23a2f8583c9d

Additional info:

```
NeoVim
        Version v0.9.5
codeium.vim
        version 1.8.37
        tag     1.8.37
        branch  main
        commit  289eb72
```

**Comment by dmbfm** [comment]
Same here. When using copilot for instance the performance is not affected. Maybe this is related to cmp?

**Comment by cleong14** [comment]
@MuhammadSawalhy it appears you're enabling/disabling `codeium.vim` in your config; not `codeium.nvim`.

Not sure if you meant to open the issue here but you may want to open it in [Exafunction/codeium.vim](https://github.com/Exafunction/codeium.vim) instead.

**Comment by MuhammadSawalhy** [comment]
@cleong14 Oh, thanks I didn't notice that.

I remember that I use `codeium.vim` because I need the virtual text preview of the completion instead of filling the completion list of `nvim-cmp` with many AI-generated suggestions.

There exists already an issue asking to implement the virtual text preview feature and this comment https://github.com/Exafunction/codeium.nvim/issues/14#issuecomment-1411322109 from the maintainer says: 

> I plan to do this eventually, but given that codeium.vim already does this, it's pretty low on my priority list.

Now I should choose between having this feature but make the performance bad or using `codeium.nvim` and losing this feature!

**Comment by MuhammadSawalhy** [comment]
Anyway, this issue should be in `codeium.vim` not here, I'll open an issue there.
