### ISSUE TITLE
neovim notice unavailable source names

### ISSUE THREAD

**Issue by matianhe3** [Exafunction/codeium.nvim#193]
`:CmpStatus` show unavailable source names.
install by lazyvim LazyExtras.
codeium not effect

**Comment by aliaksandr-trush** [comment]
Looks like README contains all required information https://github.com/Exafunction/codeium.nvim?tab=readme-ov-file#nvim-cmp

**Comment by stong1994** [comment]
I encountered the same error, and for me, it was a 'heartbeat failed' issue. after execute `export no_proxy=127.0.0.1` base on the solution found at https://github.com/Exafunction/codeium.nvim/issues/164, it start working!

**Comment by matianhe3** [comment]
> I encountered the same error, and for me, it was a 'heartbeat failed' issue. after execute `export no_proxy=127.0.0.1` base on the solution found at #164, it start working!

it works, thanks.
