### ISSUE TITLE
Right arrow?

### ISSUE THREAD

**Issue by aleyrizvi** [Exafunction/codeium.nvim#203]
Hi,
I just did Lazy update and most latest version of codeium is causing right arrow to add space in insert mode instead of navigating right.

My config:

```
-- return {
--   "Exafunction/codeium.vim",
--   event = "BufEnter",
--   config = function()
--     -- Change '<C-g>' here to any keycode you like.
--     vim.keymap.set("i", "<C-g>", function()
--       return vim.fn["codeium#Accept"]()
--     end, { expr = true, silent = true })
--     vim.keymap.set("i", "<c-;>", function()
--       return vim.fn["codeium#CycleCompletions"](1)
--     end, { expr = true, silent = true })
--     vim.keymap.set("i", "<c-,>", function()
--       return vim.fn["codeium#CycleCompletions"](-1)
--     end, { expr = true, silent = true })
--     vim.keymap.set("i", "<c-x>", function()
--       return vim.fn["codeium#Clear"]()
--     end, { expr = true, silent = true })
--   end,
-- }
```

![image](https://github.com/Exafunction/codeium.nvim/assets/1640511/e7e92798-2f70-479c-b003-2461fbd49e9c)

Codeium commit: 625a5cf

My nvim config: https://github.com/aleyrizvi/nvim-config

**Comment by aliaksandr-trush** [comment]
Looks like you are using codeium.vim, but not codeium.nvim plugin. Please use correct plugin space: https://github.com/Exafunction/codeium.nvim/issues

**Comment by aleyrizvi** [comment]
> Looks like you are using codeium.vim, but not codeium.nvim plugin. Please use correct plugin space: https://github.com/Exafunction/codeium.vim/issues

Same with codeium.nvim

**Comment by aliaksandr-trush** [comment]
> > Looks like you are using codeium.vim, but not codeium.nvim plugin. Please use correct plugin space: https://github.com/Exafunction/codeium.vim/issues
> 
> Same with codeium.nvim

In codeium.nvim completion managing by nvim-cmp plugin. So, for codeium.nvim you need to take a look into your keymaps for nvim-cmp.

**Comment by aliaksandr-trush** [comment]
Fixed in https://github.com/Exafunction/codeium.vim/pull/398
