### ISSUE TITLE
My codium isnt working well with my nvim setup

### ISSUE THREAD

**Issue by AtomicPositron** [Exafunction/codeium.nvim#226]
![Screenshot from 2024-09-24 23-11-27](https://github.com/user-attachments/assets/d02c6dce-f9ad-4ad2-b8fe-2ed9adbd0e32)
![Screenshot from 2024-09-24 23-09-16](https://github.com/user-attachments/assets/4f07d992-1a71-481a-99a2-9294b813e74b)
![Screenshot from 2024-09-24 23-09-08](https://github.com/user-attachments/assets/09e57fa0-8571-4e69-b4bf-7c02fde17276)
![Screenshot from 2024-09-24 23-12-23](https://github.com/user-attachments/assets/088e14b0-9482-4e27-a647-cccdc053ed16)

**Comment by DimasPradana** [comment]
same with me, there are some errors with details "cockroach.errorspb.EncodedError"
the log file attached below


[codeium.log.log](https://github.com/user-attachments/files/17123385/codeium.log.log)

**Comment by plague-doctor** [comment]
Same issue after the latest update (commit f1b1f2c).

**Comment by daoduytan** [comment]
Same issue

**Comment by ziriuz84** [comment]
I think It will be solved with #229. I tried to modify source.lua and now it's ok

**Comment by ziriuz84** [comment]
> > I think It will be solved with #229. I tried to modify source.lua and now it's ok
> 
> How and in what way did you modify it 

Simply applying changes that I see in #229

**Comment by plsdev89** [comment]
Facing same issue.

**Comment by plsdev89** [comment]
I confirmed that PR #229 has been merged, and everything is now working.
