### ISSUE TITLE
How to choose a model?

### ISSUE THREAD

**Issue by goququ** [Exafunction/codeium.nvim#227]
Hi all. I want to choose gpt4 model. How could I do it?

Thanks!

**Comment by KyrillGobber** [comment]
The only thing I found is opening the chat, and then pick the model in the options there

I don't know if that sets it for the autocomplete as well

**Comment by saranshsaini** [comment]
You can choose 4o in chat. That won't be used for autocomplete (we have custom models that provide better quality and latency for autocomplete).
