### ISSUE TITLE
Codeium not working and not log output

### ISSUE THREAD

**Issue by bschnitz** [Exafunction/codeium.nvim#228]
After install and configuring the auth-token, codeium does not work for me.

Expected Behaviour:
Ghost Text appears after writing `def fib(n):` in a python-file in neovim.

Actual Behaviour:
Nothing related to codeium appears.

Additional info:
There is no error message and no log file in `~/.cache/nvim/codeium`.

Edit:
I removed some comments about the language server failing when starting it manually. That was misleading, as I started it with the wrong parameters.

**Comment by aliaksandr-trush** [comment]
If you want to have Ghost Text you need to use codeium.vim plugin instead: https://github.com/Exafunction/codeium.vim
This one requires nvim-cmp configuration https://github.com/Exafunction/codeium.nvim?tab=readme-ov-file#nvim-cmp

**Comment by bschnitz** [comment]
Ah, ok, thank You! Closing this now.
