### ISSUE TITLE
Codeium <cmd> does not work

### ISSUE THREAD

**Issue by aftab0094** [Exafunction/codeium.nvim#249]
I have installed the plugin, the way said but :Codeium does not even appear/work in normal mode

**Comment by aftab0094** [comment]
I have windows system, if that helps...

**Comment by fruitsaladchan** [comment]
yea same. 
im using arch + lazy and the :Codeium command doesn't show up. i also tried [codeium.vim](https://github.com/Exafunction/codeium.vim) and that works but i didn't like the ghost text

**Comment by aftab0094** [comment]
In my case the build always failed in codium.vim

**Comment by aftab0094** [comment]
Found the [solution](https://github.com/frankroeder/parrot.nvim/issues/65) for this

just add a `event = "VeryLazy"` to you plugin config
