### ISSUE TITLE
Commit a7196bf introduces an error in the setup function

### ISSUE THREAD

**Issue by jpasquier** [Exafunction/codeium.nvim#255]
Hi,

Since the last commit ([a7196bf](https://github.com/Exafunction/codeium.nvim/commit/a7196bf9472b56ecac5c93c8b6eefba932b14492)), I get the following error

```
lazy.nvim Failed to run `config` for codeium.nvim
 
....local/share/nvim/lazy/codeium.nvim/lua/codeium/init.lua:41: attempt to index local 'options' (a nil value)
 
# stacktrace:
   - /codeium.nvim/lua/codeium/init.lua:41 _in_ **setup**
   - .config/nvim/lua/plugins/codeium-nvim.lua:9 _in_ **config**
   - .config/nvim/lua/config/lazy.lua:14
   - .config/nvim/init.lua:6
```

Best

**Comment by dimfeld** [comment]
Opened a PR to fix this, in the meantime if you just pass `{}` to the setup function it shouldn't hit that error.

**Comment by jpasquier** [comment]
Indeed, replacing `require('codeium').setup()` by `require('codeium').setup({})` solved the issue. Thanks!
