### ISSUE TITLE
No completion after upgrading to a7196bf

### ISSUE THREAD

**Issue by GNRSN** [Exafunction/codeium.nvim#256]
When upgrading to the latest version `a7196bf9472b56ecac5c93c8b6eefba932b14492` I am no longer getting any completion suggestions, chat still works and I'm seeing no errors on startup. 

Reverting to `ca38490ef963b066d6f686146d73213c70ef7f6b` restores completion. 

My configuration through lazy
```
  {
    "Exafunction/codeium.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "hrsh7th/nvim-cmp",
    },
    config = function()
      require("codeium").setup({
        enable_chat = true,
      })
    end,
  },
```

Added as top option through nvim-cmp
```
sources = cmp.config.sources({
  { name = "codeium" },
  ...
})
```

**Comment by xafarr** [comment]
@GNRSN What is your working configuration? I have the same config as yours and `CmpStatus` showing `codeium` as `# Unknown Source`

**Comment by GNRSN** [comment]
> @GNRSN What is your working configuration? I have the same config as yours and `CmpStatus` showing `codeium` as `# Unknown Source` 

From your picture, you ned to remove nvim-cmp from codeium.nvim dependencies, you can see my diff here https://github.com/GNRSN/dotfiles/commit/8789533f54090c667c57be9ac19517a3b233ea4b

**Comment by saranshsaini** [comment]
Hey @GNRSN, thanks for bringing this up. 
Just had a quick question about the update you recommended for the Readme. 
We currently recommend that "nvim-cmp setup happens before the codeium.nvim setup". This would mean adding nvim-cmp as a dependency for codeium.nvim (so that nvim-cmp loads first, then codeium.nvim). It seems this was not working for you?

I got this minimal setup working according to the current readme, and things seem to work fine. I was thinking it might be useful to link a minimal setup like this to the readme so that it is easier for newcomers to get things working, but before that wanted to make sure it worked with more complex setups like yours as well. 

Let me know what changes you might make to this.
https://github.com/saranshsaini/codeium.nvim-setup

**Comment by GNRSN** [comment]
> We currently recommend that "nvim-cmp setup happens before the codeium.nvim setup". This would mean adding nvim-cmp as a dependency for codeium.nvim (so that nvim-cmp loads first, then codeium.nvim). It seems this was not working for you?

You are correct, I was probably stressed when writing my original second post, I misread it as Codeium having to load first and inverting the dependencies actually fixed it for me. 

~Your repro uses the latest commit but I've just validated that this issue still persists for locally (i.e. reverting to match the readme again yields Codeium being listed as unknown source in :CmpStatus and getting no completion)~

After switch back and forth a couple of times whilst checking lazy profiling it is now working again for me with the original dependency order, and I can not figure out what changed. My current assumption is that since I did not validate that lazy had loaded Codeium, it was being lazy loaded and had not been enabled? I'm curious to how though since at the time I did not have anything in my spec that would trigger lazy loading and `config.defaults.lazy` is set to false. 

Unless somebody else can provide a repro I guess just drop this? Although the amount of reactions suggest that I was not alone in having this issue.

**Comment by ysy** [comment]
for anyone who are using LunarVim, just add following line to config.lua: 
```
table.insert(lvim.builtin.cmp.sources, { name = "codeium", max_item_count = 3})
```

**Comment by FeralSmurf** [comment]
Codeium also stopped working for me. This is how I installed it in my nvim kickstarter. 

`
return {
  {
    'Exafunction/codeium.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'hrsh7th/nvim-cmp',
    },
    config = function()
      require('codeium').setup {}
    end,
  },
}

`
Codeium Auth gives me the following message: api key saved, but I cannot access other commands, such as CodeiumEnable, for example. It used to work just fine.

**Comment by GNRSN** [comment]
> Kinda funny, but the plugin for vim (not nvim) works flawlessly.

Irrelevant, they are different plugins.

**Comment by saranshsaini** [comment]
@FeralSmurf Could you get a chance to try the example codeium nvim setup that I commented above? Trying to pinpoint where the issue is. Does that example minimal set up work for you? 

@ysy Not too familiar with how LunarVim works, does it require a different set up than LazyVim for managing plugins?

**Comment by GNRSN** [comment]
Since no one else has been able to contribute a reliable repro I will close this issue, if some one else still have problems with the latest version you can open a separate issue with a repro so that maintainers can do something about it.

**Comment by GNRSN** [comment]
@saranshsaini Sorry for the bad timing, feel free to reopen if you want to 😅

**Comment by FeralSmurf** [comment]
> @FeralSmurf Could you get a chance to try the example codeium nvim setup that I commented above? Trying to pinpoint where the issue is. Does that example minimal set up work for you?
> 
> @ysy Not too familiar with how LunarVim works, does it require a different set up than LazyVim for managing plugins?

```
return {

  -- {
  --   'Exafunction/codeium.vim',
  --   event = 'BufEnter',
  -- },

  --nvim setup alternative
  {
    'Exafunction/codeium.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'hrsh7th/nvim-cmp',
    },
    config = function()
      require('codeium').setup {
        enable_chat = true,
        -- to use virtual text, uncomment the following line
        -- virtual_text = {enabled = true}
      }
    end,
  },
```

still no joy. after Auth, no access to other Codeium functions besides Auth and Chat.
