### ISSUE TITLE
Support chat mode

### ISSUE THREAD

**Issue by sternelee** [Exafunction/codeium.nvim#49]
Codeium for vscode support chat mode, can you do it for nvim ? And interaction can be like Bryley/neoai.nvim

**Comment by rjshrjndrn** [comment]
This will be awesome.

**Comment by devenv** [comment]
This was three years ago.

**Comment by WikiLiu** [comment]
In vim version, codeium#Chat() maybe supported chat. When will developing for neovim?

**Comment by NONVME** [comment]
done [here](https://github.com/Exafunction/codeium.nvim/commit/a070f57c0f54bd940436b94c8b679bcad5a48811)

**Comment by xbc5** [comment]
@WikiLiu @devenv @rjshrjndrn @sternelee
