### ISSUE TITLE
threw error on `:codeium auth`

### ISSUE THREAD

**Issue by NormTurtle** [Exafunction/codeium.nvim#59]
> issue remaned from ~~plenary throw's error on :codeium auth~~
`please look at the info section for better understanding `
### issue 
1 . whenever i open nvim it just show `downloading server` 99% 
surely my net is slow but that is the whole point of using neovim! efficient and low resources RIGHT ?
but , after waiting for like 2 min many times statusline shows `codeium.nvim : server updaetd ` then i restart nvim guess what 
again the blissfull screen `downloading server ` *-*  im tried of this 
2. server is still not installed! 🤷 idk reallly , after waiting a long time 15 min i did `:codeium AUTH` 
here is the output 
```log
vCodeium.nvim: server downloaded
unpacking server
Codeium.nvim: server unpacked
Codeium.nvim: server updated
Error executing Lua callback: ...0/.cache/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:106: uuidgen: Executable not found
stack traceback:
	...0/.cache/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:106: in function 'job'
	..._0/.cache/nvim-data/lazy/codeium.nvim/lua/codeium/io.lua:191: in function 'get_command_output'
	..._0/.cache/nvim-data/lazy/codeium.nvim/lua/codeium/io.lua:315: in function 'generate_uuid'
	...0/.cache/nvim-data/lazy/codeium.nvim/lua/codeium/api.lua:76: in function 'authenticate'
	.../.cache/nvim-data/lazy/codeium.nvim/lua/codeium/init.lua:20: in function <.../.cache/nvim-data/lazy/codeium.nvim/lua/codeium/init.lua:17>
stack traceback:
	[C]: in function 'error'
	...0/.cache/nvim-data/lazy/plenary.nvim/lua/plenary/job.lua:106: in function 'job'
	..._0/.cache/nvim-data/lazy/codeium.nvim/lua/codeium/io.lua:191: in function 'get_command_output'
	..._0/.cache/nvim-data/lazy/codeium.nvim/lua/codeium/io.lua:315: in function 'generate_uuid'
	...0/.cache/nvim-data/lazy/codeium.nvim/lua/codeium/api.lua:76: in function 'authenticate'
	im.api.nvim_create_user_command('ConfigReload', ':h k', { desc = 'Reload config' })
```
i dont understand that 🌟 gibberish 🌟 correctly :( 

### info 

minimal config [lazy](https://github.com/jcdickinson/codeium.nvim#lazynvim) install
```lua 
{
    "jcdickinson/codeium.nvim",
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
    config = function()
        require("codeium").setup({
        })
    end
},
````
OS : WINDOW 11  || yes i hate being Microsoft user but i am stuck | 
nvim -v : `NVIM v0.10.0-dev` & `NVIM v0.9.1` both test fails

## many suggestions
1. please update the readme for the following 
- add info about windows at http.nvim as
Not supported on [Windows]( https://github.com/jcdickinson/http.nvim/issues/1)
- show default values of [option](https://github.com/jcdickinson/codeium.nvim#options)
2. update the language [server](https://github.com/Exafunction/codeium/releases) 

note : i dont like writing basically post that are boring to write , so please consider that im still learning english 
there is meant to be many english mistakes please dont mind , also no serious manner , just some chill 👍  thanks

**Comment by WillEhrendreich** [comment]
Do you have uuidgen installed? because it says it can't find it, so it's not on your PATH environment variable or something. I assume you're on linux or mac, otherwise, if you're on windows the plugin should generate a uuid instead of caring whether or not uuidgen is installed. 

Perhaps we should make the self generation a default instead of having external dependencies, @jcdickinson?

**Comment by NormTurtle** [comment]
i apologize i dont remremer what happened that day of test exactly! so im remaking the issue again 

by editing the content above thanks !

**Comment by pqn** [comment]
Closing this since https://github.com/Exafunction/codeium.nvim/pull/105 removed the uuidgen requirement (although we should update the README to indicate this)
