### ISSUE TITLE
Codeium Auth doesn't work on windows 11 and WSL

### ISSUE THREAD

**Issue by Zaenalabidin57** [Exafunction/codeium.nvim#69]
i'm having an issue when using this plugin in windows 11, it get an error when trying to :Codeium Auth, then it show an error,
![image](https://github.com/jcdickinson/codeium.nvim/assets/118181082/89e284a9-5633-4be4-ada2-b3bbc53fb625)

im using lazy and NVChad,

then i tried install it with lazy and nvchad in WSL ubuntu, it ran fine but after i paste the key it got an error 
![image](https://github.com/jcdickinson/codeium.nvim/assets/118181082/cf6e141a-973b-4aea-a1f3-3f27c522c7f8)

im using Windows 11 Home Insider Preview Single Language, 
im sorry if this issue are duplicate with the one in https://github.com/jcdickinson/codeium.nvim/issues/59

**Comment by DaikyXendo** [comment]
Same problem on macos 
(nvim 0.9.0
macos ventura)

**Comment by pqn** [comment]
Resolved by https://github.com/Exafunction/codeium.nvim/pull/74 and https://github.com/Exafunction/codeium.nvim/pull/100
