### ISSUE TITLE
Issue with Codeium Auth

### ISSUE THREAD

**Issue by ChrisGVE** [Exafunction/codeium.nvim#70]
Using LazyVim config on a Mac and when keying Codeium Auth, Safari is triggered and there is a key generated but on neovim side I receive the following error

 Error  19:54:14 msg_show.lua_error Error executing vim.schedule lua callback: ...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:5: attempt to call field 'inputsecret' (a nil value)
stack traceback:
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:5: in function 'get_key'
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:90: in function 'callback'
	...e/nvim/lazy/codeium.nvim/lua/codeium/views/auth-menu.lua:122: in function 'on_choice'
	...are/nvim/lazy/dressing.nvim/lua/dressing/select/init.lua:78: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

I have tried to deactivate dressing.nvim but I get the same problem.

As always I assume an operator error but in this case I am not able to detect/correct what I am doing wrong. Any help would be appreciated

**Comment by ariel-frischer** [comment]
Had the same error I changed `inputsecret` to just `input` and it worked.

**Comment by ariel-frischer** [comment]
I guess neovim doesn't have `vim.ui.inputsecret` implemented yet? https://github.com/neovim/neovim/issues/18781

**Comment by ChrisGVE** [comment]
Thanks guys, indeed replacing inputsecret to input did work for me.

**Comment by DieracDelta** [comment]
Where are you making the `inputsecret` to `input` change?

**Comment by jellydn** [comment]
This is a workaround until that issue has resolved. I've pinned the version to before that release with below config.

```lua
-- Add Codeium support, pin to stable version due to crash on input auth key
      {
        "jcdickinson/codeium.nvim",
        commit = "b1ff0d6c993e3d87a4362d2ccd6c660f7444599f",
        config = true,
      },
```
