### ISSUE TITLE
expand-archive does not help windows users.. my bad. 

### ISSUE THREAD

**Issue by WillEhrendreich** [Exafunction/codeium.nvim#76]
hey, the expand archive fix i had in this 

https://github.com/jcdickinson/codeium.nvim/blob/87266755af9e1e1ae96355c2fc430d865aff0331/lua/codeium/io.lua#L331

is not actually capable of unzipping gz files. 

that was a bad pr, and I didn't realize it at the time. I am not entirely sure that my fork fixes it yet, but there is some work in it to address it. 

https://github.com/WillEhrendreich/codeium.nvim

**Comment by WillEhrendreich** [comment]
hey @pqn, just wondering if we could get the readme fixed in regard to this issue. gzip is needed, expand-archive does not work on gz files. there are ways to download gzip in a powershell script that I've seen, but I don't know how to implement it, or where i saw it, because I have gzip installed, and it works just fine for me because of it, so due to time constraints ive had to move on. The readme should at least reflect that for new users to see.

**Comment by pqn** [comment]
https://github.com/Exafunction/codeium.vim/blob/main/powershell/gzip.ps1
https://github.com/Exafunction/codeium.vim/blob/45dd945883c2ff87553d78710797ad7a2602b269/autoload/codeium/server.vim#L176

We've implemented this in the `codeium.vim` extension already. Is this something easy to adapt for you? In that case, happy to accept a PR with the fix.
