### ISSUE TITLE
Does this plugin depends on curl?

### ISSUE THREAD

**Issue by cxwx** [Exafunction/codeium.nvim#83]
Hi all,
I found that if I set my `.curlrc` with proxy the codeium not work correctly, because my proxy is not connect to interenet,
So how could I avoid that?
Could I set codeium itself, not using system curl?

**Comment by cxwx** [comment]
> Hi all, I found that if I set my `.curlrc` with proxy the codeium not work correctly, because my proxy is not connect to interenet, So how could I avoid that?
Could I set proxy for codeium itself?

**Comment by jcdickinson** [comment]
The problem is that the codeium local proxy does not use curl, but the plugin does. I'll add support for proxy config.

**Comment by wqk151** [comment]
I have the same issue, codeium can not work when proxy is running,disable the proxy agent can work normally.

**Comment by pqn** [comment]
The language server binary should respect environment proxy variables. Maybe you can try setting something like `HTTP_PROXY`?

**Comment by wqk151** [comment]
Yes, i export the `http_proxy=http://127.0.0.1:7890/` and `https_proxy=http://127.0.0.1:7890/` in the terminal,codeium can not work. If i cancel the  environment variables works well.

**Comment by gpncarl** [comment]
In my case, the encoding type of the http response is gzip, so my proxy server assume it's transfer-encoding is chuncked, and removed the content-length in the header.
As a result, all curl process are hang

BTW, it's wired the response of languageserver use gzip without chuncked

**Comment by pqn** [comment]
If the curl component is having a problem, you can use `noproxy` in `.curlrc` to avoid localhost/127.0.0.1/codeium.com subdomains. Similarly, the Codeium binary should respect the `NO_PROXY` environment variable. And if you want these components to respect your proxy settings, they will do so by default.

**Comment by nanmoumou** [comment]
can we use vim.g.copilot_proxy like we do with copilot using parameters similar to proxy to determine whether to use a proxy
